export const EVENT_ACTION = "ACTION_EVENT";
export const EVENT_DELETED = "DELETED_EVENT";
export const EVENT_MOVED = "MOVED_EVENT";
export const EVENT_REDRAW = "REDRAW_EVENT";
export const EVENT_NEW = "NEW_EVENT";
export const EVENT_LOADED = "LOADED_EVENT";
export const EVENT_LOADING = "LOADING_EVENT";
export const EVENT_UPDATED = "UPDATED_EVENT";

// For saving purposes (place an item, move an item, create a wall, move a wall...)
export const EVENT_ACTION_DONE = "ACTION_DONE_EVENT";

export const EVENT_SAVED = "SAVED_EVENT";
export const EVENT_CHANGED = "CHANGED_EVENT";
export const EVENT_GLTF_READY = "GLTF_READY_EVENT";

export const EVENT_ITEM_LOADING = "ITEM_LOADING_EVENT";
export const EVENT_ITEM_LOADED = "ITEM_LOADED_EVENT";
export const EVENT_ITEM_REMOVED = "ITEM_REMOVED_EVENT";
export const EVENT_ITEM_SELECTED = "ITEM_SELECTED_EVENT";
export const EVENT_ITEM_UNSELECTED = "ITEM_UNSELECTED_EVENT";

export const EVENT_MODE_RESET = "MODE_RESET_EVENT";
export const EVENT_CAMERA_MOVED = "CAMERA_MOVED_EVENT";
export const EVENT_CAMERA_VIEW_CHANGE = "CAMERA_VIEW_CHANGE_EVENT";

export const EVENT_WALL_CLICKED = "WALL_CLICKED_EVENT";
export const EVENT_FLOOR_CLICKED = "FLOOR_CLICKED_EVENT";
export const EVENT_NOTHING_CLICKED = "NOTHING_CLICKED_EVENT";

export const EVENT_ROOM_NAME_CHANGED = "CHANGED_ROOM_NAME_EVENT";

export const EVENT_CORNER_ATTRIBUTES_CHANGED = "CORNER_ATTRIBUTES_CHANGED_EVENT";
export const EVENT_WALL_ATTRIBUTES_CHANGED = "WALL_ATTRIBUTES_CHANGED_EVENT";
export const EVENT_ROOM_ATTRIBUTES_CHANGED = "ROOM_ATTRIBUTES_CHANGED_EVENT";

export const EVENT_CORNER_2D_CLICKED = "CORNER_CLICKED_2D_EVENT";
export const EVENT_WALL_2D_CLICKED = "WALL_CLICKED_2D_EVENT";
export const EVENT_ROOM_2D_CLICKED = "ROOM_CLICKED_2D_EVENT";

export const EVENT_CORNER_2D_DOUBLE_CLICKED = "CORNER_DOUBLE_CLICKED_2D_EVENT";
export const EVENT_WALL_2D_DOUBLE_CLICKED = "WALL_DOUBLE_CLICKED_2D_EVENT";
export const EVENT_ROOM_2D_DOUBLE_CLICKED = "ROOM_DOUBLE_CLICKED_2D_EVENT";

export const EVENT_CORNER_2D_HOVER = "CORNER_HOVER_2D_EVENT";
export const EVENT_WALL_2D_HOVER = "WALL_HOVER_2D_EVENT";
export const EVENT_ROOM_2D_HOVER = "ROOM_HOVER_2D_EVENT";

export const EVENT_3D_FURNITURE_CLICKED = "FURNITURE_CLICKED_3D_EVENT";
export const EVENT_3D_FURNITURE_MOVED = "FURNITURE_MOVED_3D_EVENT";
export const EVENT_3D_FURNITURE_ROTATED = "FURNITURE_ROTATED_3D_EVENT";

export const EVENT_2D_TEXT_CLICKED = "TEXT_CLICKED_2D_EVENT";
export const EVENT_2D_TEXT_HOVER = "TEXT_MOVED_2D_HOVER";
export const EVENT_2D_TEXT_MOVED = "TEXT_MOVED_2D_EVENT";

export const EVENT_2D_IMAGE_CLICKED = "IMAGE_CLICKED_2D_EVENT";
export const EVENT_2D_IMAGE_HOVER = "IMAGE_MOVED_2D_HOVER";
export const EVENT_2D_IMAGE_MOVED = "IMAGE_MOVED_2D_EVENT";
